site_name: DMFF
nav:
  - Home: index.md
  - User Guide:
    - Introduction: user_guide/readme.md
    - getting started: user_guide/get_start.md
  - Dev Guide:
    - Introduction: dev_guide/readme.md
  - Modules:
    - ADMP: 
      - Introduction: admp/readme.md
  - About: about.md

theme: readthedocs
